services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: x-road-api
    container_name: x-road-api
    depends_on:
      - db
    ports:
      - "5000:5000"
    pull_policy: build
    restart: unless-stopped
  db:
    image: mongo
    container_name: x-road-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    pull_policy: always
    volumes:
      - ./data:/data/db